language: python
python:
  - 3.5
  - 3.6
  - 3.7
script:
  - isort --check-only --diff || exit 1
  - yapf --diff --recursive ./city_scrapers/ ./tests/ || exit 1
  - flake8
  - pytest
  - if [ $TRAVIS_PULL_REQUEST == 'false' ];
    then echo "Not a pull request, ignoring";
    else git diff --name-only --diff-filter=AM $TRAVIS_COMMIT_RANGE | grep -Pio '(?<=/spiders/).*(?=\.py)' | xargs scrapy validate;
    fi
before_deploy:
  - export PYTHONPATH=$(pwd):$PYTHONPATH
  - export SCRAPY_SETTINGS_MODULE=city_scrapers.settings.prod
deploy:
  - skip_cleanup: true
    provider: script
    script: scrapy runall -s LOG_ENABLED=False
    on:
      python: 3.6
      branch: master
      condition: $TRAVIS_EVENT_TYPE = cron
after_deploy:
  - scrapy combinefeeds -s LOG_ENABLED=False
